name = "recipe-book"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

# מסד התגובות. את database_id מקבלים מהפקודה:
#   npx wrangler d1 create recipe-book
[[d1_databases]]
binding = "DB"
database_name = "recipe-book"
database_id = "75ddaaff-a797-4e47-b1df-169170a6d2d8"
